### ISSUE TITLE
[问题反馈] clone下来的demo无法正常运行

### ISSUE THREAD

**Issue by FrankFan** [zhengjiaqi/taro-demo-swan#1]
## 复现步骤
1. git clone 该 repo，
2. 使用 `npm i`安装依赖成功
3. 运行 `npm run dev:swan` 
4. 使用百度开发者工具打开 dist 目录
5. 运行结果如图：
![image](https://user-images.githubusercontent.com/1589433/63070719-edd4a080-bf4e-11e9-9eaa-d08a1581e355.png)

## 运行环境

➜  ~ taro info
👽 Taro v1.3.11

  Taro CLI 1.3.11 environment info:
    System:
      OS: macOS 10.14.3
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 11.2.0 - ~/.nvm/versions/node/v11.2.0/bin/node
      npm: 6.10.1 - ~/.nvm/versions/node/v11.2.0/bin/npm

**Comment by zhengjiaqi** [comment]
项目配置已更新，请更新代码后重新安装依赖

**Comment by FrankFan** [comment]
@zhengjiaqi  按照你说的，重新`git pull`拉到了最新代码，重新安装了依赖，但是百度开发者工具中依然无法预览出正确内容。

![image](https://user-images.githubusercontent.com/1589433/63148434-bdb2fd80-c033-11e9-803c-c94da46be23d.png)


你那边是正常的吗？

**Comment by zhengjiaqi** [comment]
![image.png](https://i.loli.net/2019/08/16/VBL4gaWFAdfyNt8.png)
我这里是可以的，你试试删除node_modules 与 package-lock 重新安装依赖
